# Generated by Django 4.2 on 2023-07-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("batch_start_day", models.DateField()),
                ("class_name", models.CharField(max_length=50)),
                ("board", models.CharField(max_length=50)),
                ("mobile_number", models.CharField(max_length=20)),
                (
                    "alternate_mobile_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("school_name", models.CharField(max_length=100)),
                ("parent_name", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                (
                    "registration_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tution_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dp_paid_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("emi", models.BooleanField(default=False)),
                (
                    "emi_per_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
