# Generated by Django 4.2 on 2023-07-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissionapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="emi",
            field=models.CharField(max_length=255),
        ),
    ]
